# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'switcher'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'rouge'
end

group :development do
  gem 'capistrano', '~> 3.16', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma', require: false
  gem 'capistrano-rbenv', github: 'capistrano/rbenv', require: false
end